### ISSUE TITLE
Turkish Language PLZ

### ISSUE THREAD

**Issue by Medullitus** [watchakorn-18k/Language-Translation-App-using-AI#2]
Hello,

Thank you for the project. I wanna use it to translate texts in the game that I play in English. Can you add Turkish language too please?

**Comment by watchakorn-18k** [comment]
Can you change language follow here :
![image](https://github.com/watchakorn-18k/Language-Translation-App-using-AI/assets/74919942/f38d274e-9323-42b8-b0ee-42435f96bc73)

![image](https://github.com/watchakorn-18k/Language-Translation-App-using-AI/assets/74919942/d3c89630-3752-4300-a51d-a724aea13002)
